name = "RipsererPrep"
uuid = "28fba1bf-e12c-44a1-af44-66aee64b468f"
authors = ["Chris Johnson"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
